### ISSUE TITLE
ENH improve st in ADMM solver

### ISSUE THREAD

**Issue by tomMoral** [benchopt/benchmark_tv_1d#9]
The ADMM solver could be improved by removing the `abs` then `sign` in 
https://github.com/benchopt/benchmark_tv_1d/blob/d0a8a54ffa150ab75189540abb07d7388efceb9b/solvers/python-ADMM.py#L59

**Comment by EnLAI111** [comment]
It's done! I think that it should be just
```w -= np.clip(w, -mu, mu) ```

**Comment by tomMoral** [comment]
Yes sorry, I wrote that too quick :)
